# Generated by Django 4.2.11 on 2024-03-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfinityFinance', '0005_account_data_bills_customer_data_ecs_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account_Data',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Customer_Data',
            new_name='Customer',
        ),
    ]
