# Generated by Django 5.0.3 on 2024-03-26 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfinityFinance', '0008_alter_wallet_account_number_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='ECS_ID',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Accno',
            new_name='Account_number',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Accno',
            new_name='Account_number',
        ),
        migrations.DeleteModel(
            name='ECS_Data',
        ),
    ]
