# Generated by Django 5.0.3 on 2024-03-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfinityFinance', '0010_transaction_delete_bills_delete_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
